version: "3.2"
services:
  app:
    command: node src/server.js
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - published: ${APP_PORT:-3002}
        target: 3000
    volumes:
      - .:/app/
    environment:
      AUTH_SERVER: ${AUTH_SERVER}
      MOVIE_SERVER: ${MOVIE_SERVER}
      QUERY_SERVER: ${QUERY_SERVER}
