version: "3.2"
services:
  app:
    command: node src/server.js
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - published: ${APP_PORT:-3003}
        target: 3000
    volumes:
      - .:/app/
    environment:
      EVENT_BUS_SERVER: ${EVENT_BUS}
